### ISSUE TITLE
Pipeline Job isn't triggered 

### ISSUE THREAD

**Issue by galindro** [jenkinsci/bitbucket-push-and-pull-request-plugin#156]
Well, I see other people complaining about the same issue that I have and faced that the majority of them made some mistakes on the configuration. Perhaps opening this issue, we can find together the root cause of my issue. 

My problem is simple: Bitbucket push and pull request plugin isn't triggering job when it receives the webhook call from Bitbucket Server. **I can manually trigger jobs.** This means that there is no issues with git plugin configuration.

I'll try to share with you as much info as possible:

Plugin Version: **2.6.3**
Jenkins Version: **2.263.1**
Jenkins Job Type: **Pipeline script from SCM**
Triggered via: **Atlassian Bitbucket server v6.7.3**

### Plugin logs

```bash
Dec 07, 2020 9:17:53 AM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
Received input stream over Bitbucket hook notification:{"eventKey":"pr:opened","date":"2020-12-07T10:17:53+0100","actor":{"name":"bruno.galindro","emailAddress":"bruno.galindro@mydomain","id":1758,"displayName":"Bruno Galindro da Costa","active":true,"slug":"bruno.galindro","type":"NORMAL","links":{"self":[{"href":"https://mybitbucket.mydomain/users/bruno.galindro"}]}},"pullRequest":{"id":215,"version":0,"title":"fix: update aws-ebs-csi-driver helm chart to 0.6.1 to prevent ebs-csi-node pod be scheduled on fargate nodes","state":"OPEN","open":true,"closed":false,"createdDate":1607332673305,"updatedDate":1607332673305,"fromRef":{"id":"refs/heads/upgrade-aws-ebs-csi-driver","displayId":"upgrade-aws-ebs-csi-driver","latestCommit":"126503d3471aa1aaae3d9edf444bd87a488d363a","repository":{"slug":"myrepo","id":476,"name":"myrepo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"IT","id":44,"name":"IT","description":"IT related repositories. Owner: Bruno Galindro","public":false,"type":"NORMAL","links":{"self":[{"href":"httpsmy://bitbucket.mydomain/projects/IT"}]}},"public":false,"links":{"clone":[{"href":"https://mybitbucket.mydomain/scm/myrepo.git","name":"http"},{"href":"ssh://git@mybitbucket.mydomain:7999/myrepo.git","name":"ssh"}],"self":[{"href":"httpsmy://bitbucket.mydomain/projects/IT/repos/myrepo/browse"}]}}},"toRef":{"id":"refs/heads/master","displayId":"master","latestCommit":"43fbe20778cfcf2683888031055f062c5c673932","repository":{"slug":"myrepo","id":476,"name":"myrepo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"IT","id":44,"name":"IT","description":"IT related repositories. Owner: Bruno Galindro","public":false,"type":"NORMAL","links":{"self":[{"href":"https://mybitbucket.mydomain/projects/IT"}]}},"public":false,"links":{"clone":[{"href":"https://mybitbucket.mydomain/scm/myrepo.git","name":"http"},{"href":"ssh://git@mybitbucket.mydomain:7999/myrepo.git","name":"ssh"}],"self":[{"href":"https://mybitbucket.mydomain/projects/IT/repos/myrepo/browse"}]}}},"locked":false,"author":{"user":{"name":"bruno.galindro","emailAddress":"bruno.galindro@mydomain","id":1758,"displayName":"Bruno Galindro da Costa","active":true,"slug":"bruno.galindro","type":"NORMAL","links":{"self":[{"href":"https://mybitbucket.mydomain/users/bruno.galindro"}]}},"role":"AUTHOR","approved":false,"status":"UNAPPROVED"},"reviewers":[],"participants":[],"links":{"self":[{"href":"https://mybitbucket.mydomain/projects/IT/repos/myrepo/pull-requests/215"}]}}}
Dec 07, 2020 9:17:53 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Received x-event-key: pr:opened from Bitbucket
Dec 07, 2020 9:17:53 AM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the payload is: {"actor":{"name":"bruno.galindro","emailAddress":"bruno.galindro@mydomain","id":"1758","displayName":"Bruno Galindro da Costa","active":true,"slug":"bruno.galindro","type":"NORMAL","links":{"clone":[],"self":[{"href":"https://mybitbucket.mydomain/users/bruno.galindro"}]}},"pullRequest":{"id":215,"version":0,"title":"fix: update aws-ebs-csi-driver helm chart to 0.6.1 to prevent ebs-csi-node pod be scheduled on fargate nodes","state":"OPEN","open":true,"closed":false,"createdDate":1607332673305,"updatedDate":1607332673305,"locked":false,"author":{"active":false},"reviewers":[],"participants":[],"links":{"clone":[],"self":[{"href":"httpsmy://bitbucket.mydomain/projects/IT/repos/myrepo/pull-requests/215"}]},"fromRef":{"id":"refs/heads/upgrade-aws-ebs-csi-driver","displayId":"upgrade-aws-ebs-csi-driver","latestCommit":"126503d3471aa1aaae3d9edf444bd87a488d363a","repository":{"slug":"myrepo","id":"476","name":"myrepo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"IT","id":"44","name":"IT","links":{"clone":[],"self":[{"href":"httpsmy://bitbucket.mydomain/projects/IT"}]},"public":false,"type":"NORMAL"},"links":{"clone":[{"href":"https://mybitbucket.mydomain/scm/myrepo.git","name":"http"},{"href":"ssh://git@mybitbucket.mydomain:7999/myrepo.git","name":"ssh"}],"self":[{"href":"https://mybitbucket.mydomain/projects/IT/repos/myrepo/browse"}]},"public":false}},"toRef":{"id":"refs/heads/master","displayId":"master","latestCommit":"43fbe20778cfcf2683888031055f062c5c673932","repository":{"slug":"myrepo","id":"476","name":"myrepo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"IT","id":"44","name":"IT","links":{"clone":[],"self":[{"href":"httpsmy://bitbucket.mydomain/projects/IT"}]},"public":false,"type":"NORMAL"},"links":{"clone":[{"href":"https://mybitbucket.mydomain/scm/myrepo.git","name":"http"},{"href":"ssh://git@mybitbucket.mydomain:7999/myrepo.git","name":"ssh"}],"self":[{"href":"https://mybitbucket.mydomain/projects/IT/repos/myrepo/browse"}]},"public":false}}},"changes":[]}
Dec 07, 2020 9:17:53 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPayloadProcessorFactory createProcessor
Create BitBucketPPRPullRequestServerPayloadProcessor
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor
Processing BitBucketPPREvent [event=pr, action=opened]
Dec 07, 2020 9:17:53 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.observer.BitBucketPPRObserverFactory createObservable
Add BitBucketPPRPullRequestServerObserver for BitBucketPPREvent [event=pr, action=opened]
Dec 07, 2020 9:17:53 AM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the selected payload processor is: io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor@760d3a19
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRPullRequestServerAction
BitBucketPPRPullRequestServerAction was called.
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering remote [https://mybitbucket.mydomain/scm/myrepo.git, ssh://git@mybitbucket.mydomain:7999/myrepo.git]
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job Terraform aws-eks - Bitbucket webhook
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform - JcasC » Terraform aws-eks - Bitbucket webhook
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform - JcasC » Terraform aws-eks - Bitbucket webhook is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job Terraform aws-eks - Destroy Cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform - JcasC » Terraform aws-eks - Destroy Cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform - JcasC » Terraform aws-eks - Destroy Cluster is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job Terraform aws-eks - GPU nodegroup
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform - JcasC » Terraform aws-eks - GPU nodegroup
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform - JcasC » Terraform aws-eks - GPU nodegroup is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job Terraform aws-eks - Upgrade Cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform - JcasC » Terraform aws-eks - Upgrade Cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform - JcasC » Terraform aws-eks - Upgrade Cluster is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job myrepo-destroy-cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform » myrepo-destroy-cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform » myrepo-destroy-cluster is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job myrepo-gpu-nodegroup
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform » myrepo-gpu-nodegroup
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform » myrepo-gpu-nodegroup is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job myrepo-update-cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform » myrepo-update-cluster
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Bitbucket Trigger for job: Terraform » myrepo-update-cluster is not present. 
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job myrepo-webhook
Dec 07, 2020 9:17:53 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke Terraform » myrepo-webhook
Dec 07, 2020 9:17:53 AM FINEST io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
Sending response.
Dec 07, 2020 9:17:53 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Response sent.
```

![image](https://user-images.githubusercontent.com/4622097/101337963-a3321280-387c-11eb-862f-096a3eb4318a.png)

### Jenkins server logs
```bash
2020-12-07T09:17:53.568438103Z 2020-12-07 09:17:53.568+0000 [id=72]	INFO	i.j.p.b.BitBucketPPRHookReceiver#doIndex: Received x-event-key: pr:opened from Bitbucket
2020-12-07T09:17:53.842977564Z 2020-12-07 09:17:53.842+0000 [id=72]	INFO	i.j.p.b.p.BitBucketPPRPayloadProcessorFactory#createProcessor: Create BitBucketPPRPullRequestServerPayloadProcessor
2020-12-07T09:17:53.849902388Z 2020-12-07 09:17:53.849+0000 [id=72]	INFO	i.j.p.b.o.BitBucketPPRObserverFactory#createObservable: Add BitBucketPPRPullRequestServerObserver for BitBucketPPREvent [event=pr, action=opened]
2020-12-07T09:17:53.864809751Z 2020-12-07 09:17:53.864+0000 [id=72]	INFO	i.j.p.b.BitBucketPPRHookReceiver#doIndex: Response sent.
```

### Plugin response sent
![image](https://user-images.githubusercontent.com/4622097/101336326-a3311300-387a-11eb-96bb-5eeb3c324e6e.png)

### Job configuration
![imagem](https://user-images.githubusercontent.com/4622097/101337002-703b4f00-387b-11eb-87fc-ac2004bc7043.png)

### Bitbucket webhook configuration
![a](https://user-images.githubusercontent.com/4622097/101337521-0f604680-387c-11eb-9f36-9d0b0d17f6bc.png)

![b](https://user-images.githubusercontent.com/4622097/101337779-61a16780-387c-11eb-8697-68cb7e667035.png)

**Comment by galindro** [comment]
Forgot to sent a list of installed plugins. As you can see, the old Bitbucket plugin isn't installed.

```yaml
jquery-detached: 1.2.1
cloudbees-folder: 6.15
durable-task: 1.35
plain-credentials: 1.7
pipeline-stage-view: 2.19
blueocean-commons: 1.24.3
google-oauth-plugin: 1.0.2
metrics: 4.0.2.6
blueocean-pipeline-api-impl: 1.24.3
htmlpublisher: 1.25
handy-uri-templates-2-api: 2.1.8-1.0
github: 1.32.0
blueocean-executor-info: 1.24.3
bouncycastle-api: 2.18
kubernetes-credentials: 0.7.0
blueocean-dashboard: 1.24.3
workflow-job: 2.40
blueocean-i18n: 1.24.3
job-dsl: 1.77
pipeline-model-api: 1.7.2
workflow-step-api: 2.23
blueocean-bitbucket-pipeline: 1.24.3
kubernetes-client-api: 4.11.1
workflow-aggregator: 2.6
blueocean-jira: 1.24.3
docker-commons: 1.17
authentication-tokens: 1.4
blueocean-github-pipeline: 1.24.3
configuration-as-code: 1.46
pipeline-model-extensions: 1.7.2
blueocean-display-url: 2.4.0
okhttp-api: 3.14.9
pipeline-stage-tags-metadata: 1.7.2
plugin-util-api: 1.5.0
blueocean-config: 1.24.3
xml-job-to-job-dsl: 0.1.13
echarts-api: 4.9.0-2
workflow-multibranch: 2.22
cloudbees-bitbucket-branch-source: 2.9.5
aws-java-sdk: 1.11.854
blueocean-rest: 1.24.3
apache-httpcomponents-client-4-api: 4.5.10-2.0
ssh-credentials: 1.18.1
matrix-project: 1.18
bootstrap4-api: 4.5.3-1
blueocean-web: 1.24.3
parameterized-scheduler: 0.8
variant: 1.3
blueocean-pipeline-editor: 1.24.3
lockable-resources: 2.10
workflow-support: 3.7
branch-api: 2.6.2
display-url-api: 2.3.4
popper-api: 1.16.0-7
momentjs: 1.1.1
blueocean-personalization: 1.24.3
ace-editor: 1.1
workflow-durable-task-step: 2.37
workflow-cps-global-lib: 2.17
pipeline-stage-step: 2.5
favorite: 2.3.2
token-macro: 2.12
docker-workflow: 1.25
blueocean-jwt: 1.24.3
locale: 1.4
git-client: 3.5.1
blueocean-events: 1.24.3
git-server: 1.9
blueocean-rest-impl: 1.24.3
jsch: 0.1.55.2
checks-api: 1.1.1
blueocean-pipeline-scm-api: 1.24.3
kubernetes: 1.28.3
structs: 1.20
pipeline-rest-api: 2.19
blueocean-autofavorite: 1.2.4
git: 4.4.5
matrix-auth: 2.6.4
mercurial: 2.12
handlebars: 1.1.1
antisamy-markup-formatter: 2.1
jdk-tool: 1.4
workflow-scm-step: 2.11
pipeline-milestone-step: 1.3.1
github-branch-source: 2.9.2
snakeyaml-api: 1.27.0
pipeline-build-step: 2.13
pipeline-input-step: 2.12
oauth-credentials: 0.4
trilead-api: 1.0.12
font-awesome-api: 5.15.1-1
workflow-api: 2.40
jackson2-api: 2.12.0
terraform: 1.0.10
blueocean-git-pipeline: 1.24.3
github-api: 1.117
sse-gateway: 1.24
ansicolor: 0.7.3
script-security: 1.75
jquery3-api: 3.5.1-2
jenkins-design-language: 1.24.3
mailer: 1.32.1
bitbucket-push-and-pull-request: 2.6.3
scm-api: 2.6.4
pipeline-model-definition: 1.7.2
junit: 1.45
aws-credentials: 1.28
preSCMbuildstep: 0.3
jira: 3.1.3
pipeline-graph-analysis: 1.10
workflow-basic-steps: 2.23
windows-slaves: 1.7
pubsub-light: 1.13
credentials-binding: 1.24
slack: 2.45
blueocean: 1.24.3
command-launcher: 1.5
active-directory: 2.22
credentials: 2.3.14
workflow-cps: 2.87
blueocean-core-js: 1.24.3
pipeline-aws: 1.43
```
